// Diese Datei enthält das Mapping von Ländernamen zu Flaggen-Codes
const countryCodes = {
    // --- EUROPA & SUB-NATIONEN ---
    "germany": "de",
    "austria": "at",
    "switzerland": "ch",
    "france": "fr",
    "italy": "it",
    "spain": "es",
    "portugal": "pt",
    "netherlands": "nl",
    "belgium": "be",
    "luxembourg": "lu",
    "united kingdom": "gb",
    "uk": "gb",
    "england": "gb-eng",
    "scotland": "gb-sct",
    "wales": "gb-wls",
    "northern ireland": "gb-nir",
    "ireland": "ie",
    "isle of man": "im",
    "sweden": "se",
    "norway": "no",
    "denmark": "dk",
    "finland": "fi",
    "iceland": "is",
    "faroe islands": "fo",
    "greenland": "gl",
    "aland islands": "ax",
    "estonia": "ee",
    "latvia": "lv",
    "lithuania": "lt",
    "poland": "pl",
    "czech republic": "cz",
    "czechia": "cz",
    "slovakia": "sk",
    "hungary": "hu",
    "romania": "ro",
    "bulgaria": "bg",
    "greece": "gr",
    "turkey": "tr",
    "cyprus": "cy",
    "malta": "mt",
    "slovenia": "si",
    "croatia": "hr",
    "serbia": "rs",
    "bosnia and herzegovina": "ba",
    "montenegro": "me",
    "north macedonia": "mk",
    "albania": "al",
    "kosovo": "xk",
    "ukraine": "ua",
    "belarus": "by",
    "moldova": "md",
    "russia": "ru",
    "vatican city": "va",
    "san marino": "sm",
    "liechtenstein": "li",
    "andorra": "ad",
    "monaco": "mc",
    "gibraltar": "gi",

    // --- NORD- & MITTELAMERIKA ---
    "usa": "us",
    "united states": "us",
    "united states of america": "us",
    "canada": "ca",
    "mexico": "mx",
    "guatemala": "gt",
    "belize": "bz",
    "honduras": "hn",
    "el salvador": "sv",
    "nicaragua": "ni",
    "costa rica": "cr",
    "panama": "pa",
    "cuba": "cu",
    "jamaica": "jm",
    "haiti": "ht",
    "dominican republic": "do",
    "bahamas": "bs",
    "barbados": "bb",
    "trinidad and tobago": "tt",
    "saint lucia": "lc",
    "grenada": "gd",
    "puerto rico": "pr",
    "antigua and barbuda": "ag",
    "dominica": "dm",
    "saint kitts and nevis": "kn",
    "saint vincent and the grenadines": "vc",

    // --- SÜDAMERIKA ---
    "brazil": "br",
    "argentina": "ar",
    "chile": "cl",
    "colombia": "co",
    "peru": "pe",
    "venezuela": "ve",
    "ecuador": "ec",
    "bolivia": "bo",
    "paraguay": "py",
    "uruguay": "uy",
    "guyana": "gy",
    "suriname": "sr",
    "french guiana": "gf",

    // --- ASIEN ---
    "japan": "jp",
    "south korea": "kr",
    "north korea": "kp",
    "china": "cn",
    "taiwan": "tw",
    "india": "in",
    "pakistan": "pk",
    "bangladesh": "bd",
    "thailand": "th",
    "vietnam": "vn",
    "indonesia": "id",
    "malaysia": "my",
    "philippines": "ph",
    "singapore": "sg",
    "sri lanka": "lk",
    "nepal": "np",
    "kazakhstan": "kz",
    "uzbekistan": "uz",
    "turkmenistan": "tm",
    "kyrgyzstan": "kg",
    "tajikistan": "tj",
    "afghanistan": "af",
    "iran": "ir",
    "iraq": "iq",
    "israel": "il",
    "palestine": "ps",
    "jordan": "jo",
    "lebanon": "lb",
    "syria": "sy",
    "saudi arabia": "sa",
    "uae": "ae",
    "united arab emirates": "ae",
    "qatar": "qa",
    "kuwait": "kw",
    "oman": "om",
    "yemen": "ye",
    "georgia": "ge",
    "armenia": "am",
    "azerbaijan": "az",
    "mongolia": "mn",
    "bhutan": "bt",
    "cambodia": "kh",
    "laos": "la",
    "maldives": "mv",
    "myanmar": "mm",
    "brunei": "bn",
    "timor-leste": "tl",

    // --- AFRIKA ---
    "egypt": "eg",
    "south africa": "za",
    "nigeria": "ng",
    "kenya": "ke",
    "ethiopia": "et",
    "ghana": "gh",
    "morocco": "ma",
    "algeria": "dz",
    "tunisia": "tn",
    "libya": "ly",
    "sudan": "sd",
    "south sudan": "ss",
    "uganda": "ug",
    "tanzania": "tz",
    "zambia": "zm",
    "angola": "ao",
    "namibia": "na",
    "botswana": "bw",
    "zimbabwe": "zw",
    "mozambique": "mz",
    "madagascar": "mg",
    "senegal": "sn",
    "ivory coast": "ci",
    "cameroon": "cm",
    "congo": "cg",
    "drc": "cd",
    "democratic republic of the congo": "cd",
    "gabon": "ga",
    "mali": "ml",
    "niger": "ne",
    "chad": "td",
    "somalia": "so",
    "mauritius": "mu",
    "eritrea": "er",
    "gambia": "gm",
    "guinea": "gn",
    "guinea-bissau": "gw",
    "liberia": "lr",
    "sierra lanka": "sl",
    "togo": "tg",
    "benin": "bj",
    "burkina faso": "bf",
    "central african republic": "cf",
    "djibouti": "dj",
    "equatorial guinea": "gq",
    "rwanda": "rw",
    "burundi": "bi",
    "malawi": "mw",
    "lesotho": "ls",
    "swaziland": "sz",
    "eswatini": "sz",
    "seychelles": "sc",
    "comoros": "km",
    "cape verde": "cv",
    "sao tome and principe": "st",
    "mauritania": "mr",

    // --- OZEANIEN ---
    "australia": "au",
    "new zealand": "nz",
    "fiji": "fj",
    "papua new guinea": "pg",
    "solomon islands": "sb",
    "vanuatu": "vu",
    "samoa": "ws",
    "kiribati": "ki",
    "tonga": "to",
    "tuvalu": "tv",
    "nauru": "nr",
    "palau": "pw",
    "micronesia": "fm",
    "marshall islands": "mh"
};